version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nts-nexus-http:
    container_name: nts-nexus-http
    build:
      context: ../
      dockerfile: src/Apps/Nexus/NTS.Nexus.HTTP/Dockerfile
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017
      # CORS
      CORS_ALLOWED_ORIGINS: '["https://localhost:7077","http://localhost:7077"]'
      CORS_SUPPORT_CREDENTIALS: 'true'
      FUNCTIONS_ENABLE_CORS_CONFIGURATION: "1"
      CONTAINER_NAME: "local"
    depends_on:
      - mongodb
    ports:
      - "8080:80"

volumes:
  mongodb_data:
