global using static Not.Localization.NStrings;
global using NTS.Judge.Contracts.Features.Core;
global using NTS.Judge.Contracts.Features.Core.Dashboard;
global using NTS.Judge.Contracts.Features.Core.Handouts;
global using NTS.Judge.Contracts.Features.Core.Rankings;
global using NTS.Judge.Contracts.Features.Core.Rankings.CustomRankings;
global using NTS.Judge.Contracts.Features.Core.Rankings.FeiExport;
global using NTS.Judge.Contracts.Features.Settings;
global using NTS.Judge.Contracts.Features.Setup;
global using NTS.Judge.Contracts.Features.Setup.Athletes;
global using NTS.Judge.Contracts.Features.Setup.Clubs;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents.Combinations;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents.Competitions;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents.Loops;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents.Officials;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents.Participations;
global using NTS.Judge.Contracts.Features.Setup.ConfigureEvents.Phases;
global using NTS.Judge.Contracts.Features.Setup.Horses;
global using static NTS.Localization.NtsStrings;
