<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>false</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NTS.Contracts\NTS.Contracts.csproj" />
    <ProjectReference Include="..\..\nugets\Not.Krud\Not.Krud.csproj" />
  </ItemGroup>

</Project>
