global using Microsoft.AspNetCore.Components;
global using static Not.Localization.NStrings;
global using NTS.Judge.Contracts.Features.Core;
global using NTS.Judge.Contracts.Features.Core.Dashboard;
global using NTS.Judge.Contracts.Features.Core.Handouts;
global using NTS.Judge.Contracts.Features.Core.Rankings;
global using NTS.Judge.Contracts.Features.Core.Rankings.CustomRankings;
global using NTS.Judge.Contracts.Features.Core.Rankings.FeiExport;
global using NTS.Judge.Contracts.Features.Settings;
global using NTS.Judge.Contracts.Features.Setup;
global using NTS.Judge.Contracts.Features.Setup.Athletes;
global using NTS.Judge.Contracts.Features.Setup.Clubs;
global using NTS.Judge.Contracts.Features.Setup.Horses;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents.Combinations;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents.Competitions;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents.Loops;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents.Officials;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents.Participations;
global using NTS.Judge.Contracts.Features.Setup.UpcomingEvents.Phases;
global using NTS.Domain.Enums;
global using static NTS.Localization.NtsStrings;
