name: "[net8] PR Checks"
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  DOTNET_CORE_VERSION: 8.0.x
  SOLUTION_DIR: src
  CONFIGURATION: Release
  MAUI_PROJECT_PATH: Judge/NTS.Judge.MAUI/NTS.Judge.MAUI.csproj

jobs:
  csharpier-format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Print pull_request event
        run: |
          echo Branch:
          echo "${{ github.event.pull_request }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Provisioned automatically by GitHub
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  #

      - name: Cache Csharpier tool
        id: cache-csharpier
        uses: actions/cache@v3
        with:
          path: ~/.dotnet/tools
          key: ${{ runner.os }}-dotnet-tools-csharpier

      - name: Install Csharpier if not cached
        run: dotnet tool install -g csharpier || echo "Csharpier already installed"

      - name: Run Csharpier
        run: dotnet csharpier . 

      - name: Check for formatting changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            if [[ `git status --porcelain` ]]; then
              git commit -m "Apply Csharpier code formatting"
              git push
            else 
              echo "No formatting changes needed"
            fi
          else
            echo "No formatting changes needed"
          fi

  build:
    runs-on: ubuntu-latest
    needs: csharpier-format
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        
    #Slap on top of every build: see https://github.com/Not-Endurance/not-timing-system/issues/361
    - name: Set current workding directory env
      run: echo "CURRENT_DIR=$(pwd)/src" >> $GITHUB_ENV
    - name: Remove local-cache NuGet source
      run: dotnet nuget remove source "local-cache" --configfile ./${{ env.SOLUTION_DIR }}/NuGet.config

    - name: MAUI workloads
      run: dotnet workload restore --project ${{ env.SOLUTION_DIR }}/${{ env.MAUI_PROJECT_PATH }}

    - name: Restore
      run: dotnet restore "${{ env.SOLUTION_DIR }}"
    
    - name: Build
      run: |
        dotnet build "${{ env.SOLUTION_DIR }}" \
        --configuration "${{ env.CONFIGURATION }}" \
        --no-restore \
        -property:SolutionDir="$CURRENT_DIR"
