using Microsoft.Extensions.Options;
using Microsoft.JSInterop;
using Not.Application.Print;
using Not.Blazor.Client.Browser;
using Not.Files;
using Not.Print;

namespace NTS.Tests.Unit.Temporary;

public sealed class BrowserPrintServiceTests
{
    [Fact]
    public async Task PrintPdf_UsesBackendPdfWhenBypassIsDisabled()
    {
        var api = new RecordingPrintApiService();
        var js = new RecordingJSRuntime();
        var service = CreateService(js, api, bypassBackendPrinting: false);

        await service.PrintPdf(new NPrintDocumentRequest { FileName = "ranklist.pdf", Html = "<main />" });

        Assert.Equal(1, api.CreatePdfCalls);
        Assert.Contains("printPdfBytes", js.Invocations.Select(x => x.Identifier));
        Assert.DoesNotContain("printHtml", js.Invocations.Select(x => x.Identifier));
    }

    [Fact]
    public async Task PrintPdf_PrintsHtmlWithoutBackendWhenBypassIsEnabled()
    {
        var api = new RecordingPrintApiService();
        var js = new RecordingJSRuntime();
        var service = CreateService(js, api, bypassBackendPrinting: true);

        await service.PrintPdf(
            new NPrintDocumentRequest
            {
                Title = "Ranklist",
                FileName = "ranklist.pdf",
                Html = "<main>Ranklist body</main>",
                FooterText = "Generated by test",
                BackdropImage = "data:image/png;base64,test",
                Page = new NPrintPageOptions
                {
                    PaperFormat = NPrintPaperFormat.A5,
                    Orientation = NPrintOrientation.Landscape,
                },
            }
        );

        Assert.Equal(0, api.CreatePdfCalls);
        var printHtml = Assert.Single(js.Invocations.Where(x => x.Identifier == "printHtml"));
        var html = Assert.IsType<string>(Assert.Single(printHtml.Arguments));
        Assert.Contains("<main>Ranklist body</main>", html);
        Assert.Contains("@page", html);
        Assert.Contains("A5 landscape", html);
        Assert.Contains("Generated by test", html);
        Assert.Contains("print-backdrop", html);
        Assert.Contains("MudBlazor.min.css", html);
    }

    static BrowserPrintService CreateService(
        RecordingJSRuntime js,
        RecordingPrintApiService api,
        bool bypassBackendPrinting
    )
    {
        return new BrowserPrintService(
            js,
            api,
            Options.Create(new NPrintClientSettings { BypassBackendPrinting = bypassBackendPrinting })
        );
    }

    sealed class RecordingPrintApiService : INPrintApiService
    {
        public int CreatePdfCalls { get; private set; }

        public Task<NFile> CreatePdf(NPrintDocumentRequest request, CancellationToken cancellationToken = default)
        {
            CreatePdfCalls++;
            return Task.FromResult(new NFile(request.FileName, NFileContentTypes.Pdf, [1, 2, 3]));
        }

        public Task<NFile> CreateZip(NPrintBatchRequest request, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(new NFile(request.FileName, NFileContentTypes.Zip, [4, 5, 6]));
        }
    }

    sealed class RecordingJSRuntime : IJSRuntime, IJSObjectReference
    {
        public List<Invocation> Invocations { get; } = [];

        public ValueTask<TValue> InvokeAsync<TValue>(string identifier, object?[]? args)
        {
            Invocations.Add(new Invocation(identifier, args ?? []));
            if (typeof(TValue) == typeof(IJSObjectReference))
            {
                return ValueTask.FromResult((TValue)(object)this);
            }

            return ValueTask.FromResult(default(TValue)!);
        }

        public ValueTask<TValue> InvokeAsync<TValue>(
            string identifier,
            CancellationToken cancellationToken,
            object?[]? args
        )
        {
            Invocations.Add(new Invocation(identifier, args ?? []));
            return ValueTask.FromResult(default(TValue)!);
        }

        public ValueTask DisposeAsync()
        {
            return ValueTask.CompletedTask;
        }
    }

    sealed class Invocation
    {
        public Invocation(string identifier, IReadOnlyList<object?> arguments)
        {
            Identifier = identifier;
            Arguments = arguments;
        }

        public string Identifier { get; }
        public IReadOnlyList<object?> Arguments { get; }
    }
}
